### ISSUE TITLE
NPE in interpretation

### ISSUE THREAD

**Issue by timrobertson100** [gbif/occurrence#130]
Logs show this for [this record](https://api.gbif.org/v1/occurrence/1805890372) resulting in an `INTERPRETATION_ERROR` flag:

```
11:03:23 UTC prodcrawler1-vh ~/logs $ tail -1000 processor-interpreted.log 
WARN  [08-23 11:02:46,602+0000] [occurrence_interp_direct-2] org.gbif.occurrence.processor.interpreting.OccurrenceInterpreter:  Caught a runtime exception during interpretation
java.lang.NullPointerException: null
	at org.gbif.common.parsers.date.TemporalAccessorUtils.toDate(TemporalAccessorUtils.java:52)
	at org.gbif.common.parsers.date.TemporalAccessorUtils.toDate(TemporalAccessorUtils.java:34)
	at org.gbif.occurrence.processor.interpreting.MultiMediaInterpreter.interpretMedia(MultiMediaInterpreter.java:86)
	at org.gbif.occurrence.processor.interpreting.OccurrenceInterpreter.lambda$interpret$0(OccurrenceInterpreter.java:114)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.gbif.occurrence.processor.interpreting.OccurrenceInterpreter.interpret(OccurrenceInterpreter.java:112)
	at org.gbif.occurrence.processor.InterpretedProcessor.buildInterpreted(InterpretedProcessor.java:198)
	at org.gbif.occurrence.processor.messaging.InterpretVerbatimListener.handleMessage(InterpretVerbatimListener.java:36)
	at org.gbif.occurrence.processor.messaging.InterpretVerbatimListener.handleMessage(InterpretVerbatimListener.java:18)
	at org.gbif.common.messaging.MessageConsumer.handleCallback(MessageConsumer.java:101)
	at org.gbif.common.messaging.MessageConsumer.handleDelivery(MessageConsumer.java:65)
	at com.rabbitmq.client.impl.ConsumerDispatcher$4.run(ConsumerDispatcher.java:121)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by MattBlissett** [comment]
1) Probably the unusual date with the format `2018-01-10 03:54:06.82` isn't parsed correctly.
2) The MultimediaInterpreter isn't tolerant to this.
