### ISSUE TITLE
Confusing HTTP error codes for download requests

### ISSUE THREAD

**Issue by MattBlissett** [gbif/occurrence#299]
Removing a comma (e.g. from ) and submitting the request using Curl gives a 404 error:

```
ERROR [2023-01-18 15:03:24,111+0000] [http-nio-9011-exec-816] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
org.json.JSONException: Expected a ',' or ']' at 765 [character 766 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:521)
        at org.json.JSONArray.<init>(JSONArray.java:145)
        at org.json.JSONTokener.nextValue(JSONTokener.java:445)
        at org.json.JSONObject.<init>(JSONObject.java:262)
        at org.json.JSONObject.<init>(JSONObject.java:421)
        at org.gbif.occurrence.download.service.DownloadRequestsValidator.validate(DownloadRequestsValidator.java:73)
```

It should be 400 for bad request.

A 404 was also returned for an error:

```
ERROR [2023-01-18 15:05:46,946+0000] [http-nio-9011-exec-849] org.gbif.ws.client.ClientErrorDecoder: Client exception: {"timestamp":"2023-01-18T15:05:46.925+00:00","status":500,"error":"Internal Server Error","message":"","path":"/occurrence/download"}
ERROR [2023-01-18 15:05:46,948+0000] [http-nio-9011-exec-849] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.gbif.api.exception.ServiceUnavailableException: An internal server error occurred, please try again later] with root cause
org.gbif.api.exception.ServiceUnavailableException: An internal server error occurred, please try again later
        at org.gbif.ws.client.ClientErrorDecoder.decode(ClientErrorDecoder.java:69)
```

Which happened where occ-ws accepted the download request, but registry-ws rejected it:

```
### Cause: org.postgresql.util.PSQLException: ERROR: invalid input value for enum extension: "DNA_DERIVED_DATA"
; ERROR: invalid input value for enum extension: "DNA_DERIVED_DATA"; nested exception is org.postgresql.util.PSQLException: ERROR: invalid input value for enum extension: "DNA_DERIVED_DATA"] with root cause
org.postgresql.util.PSQLException: ERROR: invalid input value for enum extension: "DNA_DERIVED_DATA"
```

**Comment by ahakanzn** [comment]
This seems out of date and solved so I'm closing this
