### ISSUE TITLE
Submit Occurrence Downloads to K8

### ISSUE THREAD

**Issue by fmendezh** [gbif/occurrence#306]
Modify occurrence downloads to submit jobs to k8/stackable using https://github.com/gbif/stackable-spark

**Comment by muttcg** [comment]
Update:
Small downloads work, at least one of queries can complete and create a zip file.

It took a while to run completed job because of runtime issues. List of fixed issues:

- multiple classpath hells with gbif-api, elasticsearch clients, hadoop version mismatch
- added missed/new lib versions
- fixed main issue with Akka, migrated Akka from 2.0.* -> 2.5.* to support Java 11 (Spark java versions), rewrote Akka related classes to fix deleted APIs
- created downloads.properties configs
- fixed pod templates issues
- fixed Spark executer naming issue

**Comment by muttcg** [comment]
Update:
`SET hive.exec.compress.output=true;` doesn't work, error:
```
Caused by: java.lang.ClassCastException: class org.gbif.hadoop.compress.d2.D2Codec                                                                                                                                                                   
     at java.base/java.lang.Class.asSubclass(Class.java:3640)                                                                                                                                                                                         
     at org.apache.hadoop.mapred.FileOutputFormat.getOutputCompressorClass(FileOutputFormat.java:97)                                                                                                                                                  
     at org.apache.hadoop.hive.ql.exec.Utilities.getFileExtension(Utilities.java:965)                                                                                                                                                                 
     at org.apache.spark.sql.hive.execution.HiveFileFormat$$anon$1.getFileExtension(HiveFileFormat.scala:99)                                                                                                                                          
     at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.newOutputWriter(FileFormatDataWriter.scala:152)                                                                                                                          
     at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.<init>(FileFormatDataWriter.scala:146)                                                                                                                                   
     at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:317)                                                                                                                                          
     at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$21(FileFormatWriter.scala:256)                                                                                                                                    
     at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)                                                                                                                                                                            
     at org.apache.spark.scheduler.Task.run(Task.scala:136)  
```

When I delete GBIFs custom codecs, these 2 lines:
```
SET mapred.output.compression.codec=org.gbif.hadoop.compress.d2.D2Codec;
SET io.compression.codecs=org.gbif.hadoop.compress.d2.D2Codec;
```
Downloads throws:
```
Caused by: java.lang.ClassCastException: class org.apache.hadoop.io.compress.DefaultCodec                                                                                                                                                            
     at java.base/java.lang.Class.asSubclass(Class.java:3640)                                                                                                                                                                                         
     at org.apache.hadoop.mapred.FileOutputFormat.getOutputCompressorClass(FileOutputFormat.java:97)                                                                                                                                                  
     at org.apache.hadoop.hive.ql.exec.Utilities.getFileExtension(Utilities.java:965)                                                                                                                                                                 
     at org.apache.spark.sql.hive.execution.HiveFileFormat$$anon$1.getFileExtension(HiveFileFormat.scala:99)                                                                                                                                          
     at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.newOutputWriter(FileFormatDataWriter.scala:152)                                                                                                                          
     at org.apache.spark.sql.execution.datasources.SingleDirectoryDataWriter.<init>(FileFormatDataWriter.scala:146)                                                                                                                                   
     at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:317)                                                                                                                                          
     at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$21(FileFormatWriter.scala:256)                                                                                                                                    
     at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)                                                                                                                                                                            
     at org.apache.spark.scheduler.Task.run(Task.scala:136)      
```
Without `SET hive.exec.compress.output=true;` the process goes further without codecs issues.

**Comment by muttcg** [comment]
Current issue (compress = false)

` Caused by: java.lang.ClassCastException: class org.apache.hadoop.mapred.TextInputFormat cannot be cast to class org.apache.hadoop.mapred.InputFormat (org.apache.hadoop.mapred.TextInputFormat is in unnamed module of loader org.apache.spark.util.ChildFirstURLClassLoader @321b0237; org.apache.hadoop.mapred.InputFormat is in unnamed module of loader 'app')`

**Comment by timrobertson100** [comment]
Please see [here](https://github.com/timrobertson100/k8s-spark-demo/blob/main/src/main/java/org/gbif/demo/SparkHiveDemoApp.java#L30) for a demo of how to do custom compression with a Hive CTAS using Spark SQL.

In doing this I made [this commit](https://github.com/gbif/hadoop-compress/commit/f986a48d8f7ac02ff73d4f88eff0fe08f72b0927) on hadoop-compress which you need to install locally for now. I also suspect it's important to ensure all the hadoop libs are `provided` when building on m1 chipset - they should be any way to avoid bloated Jars, but I think it may be important here.
