### ISSUE TITLE
Deletion in console does not always proliferate to the records

### ISSUE THREAD

**Issue by jlegind** [gbif/occurrence#40]
I launched a deletion of 122 OBIS datasets on April 6 and 22 of those datasets did not get picked up by deletion as of April 9.
This kind of behavior has happened before so I'd like to know what is holding up the cleanup step. 
All deletions were done through the API and the datasets are all marked as 'deleted'.
This is the list of datasets with remaining records:

866a0414-f762-11e1-a439-00145eb45e9a
8427b732-f762-11e1-a439-00145eb45e9a
86078cbc-f762-11e1-a439-00145eb45e9a
866c6b78-f762-11e1-a439-00145eb45e9a
86663a78-f762-11e1-a439-00145eb45e9a
860ea088-f762-11e1-a439-00145eb45e9a
86760a98-f762-11e1-a439-00145eb45e9a
860d8130-f762-11e1-a439-00145eb45e9a
866d9228-f762-11e1-a439-00145eb45e9a
85edb2d8-f762-11e1-a439-00145eb45e9a
8608bfc4-f762-11e1-a439-00145eb45e9a
8679c142-f762-11e1-a439-00145eb45e9a
867389d0-f762-11e1-a439-00145eb45e9a
8609f1a0-f762-11e1-a439-00145eb45e9a
842dbfec-f762-11e1-a439-00145eb45e9a
86040e48-f762-11e1-a439-00145eb45e9a
866fe1e0-f762-11e1-a439-00145eb45e9a
860c496e-f762-11e1-a439-00145eb45e9a
860b21e2-f762-11e1-a439-00145eb45e9a
866eaf00-f762-11e1-a439-00145eb45e9a
866b2f1a-f762-11e1-a439-00145eb45e9a
866775be-f762-11e1-a439-00145eb45e9a

**Comment by MattBlissett** [comment]
Trace from occurrence-deleter, there are several of these in the log:

```
WARN  [04-06 21:05:55,938+0200] [occurrence_delete_dataset-5] org.gbif.common.messaging.MessageConsumer:  Error handling message [2] of type [DeleteDatasetOccurrencesMessage]. Reject and send a nack
java.lang.RuntimeException: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Fri Apr 06 21:05:55 CEST 2018, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=60303: row '4fa7b334-ce0d-4e88-aaae-2e0c138d049e|URN:catalog:CLO:EBIRD:OBS99855446' on table 'prod_e_occurrence_lookup' at region=prod_e_occurrence_lookup,4fa7b334-ce0d-4e88-aaae-2e0c138d049e|URN:catalog:CLO:EBIRD:OBS99855446,1447096271601.e68ff045ebd8d972167b9bf67efb72d0., hostname=c5n3.gbif.org,60020,1517415927036, seqNum=23123276

        at org.apache.hadoop.hbase.client.AbstractClientScanner$1.hasNext(AbstractClientScanner.java:97)
        at org.gbif.occurrence.persistence.keygen.AbstractHBaseKeyPersistenceService.findKeysByScope(AbstractHBaseKeyPersistenceService.java:126)
        at org.gbif.occurrence.persistence.OccurrenceKeyPersistenceServiceImpl.findKeysByDataset(OccurrenceKeyPersistenceServiceImpl.java:55)
        at org.gbif.occurrence.cli.dataset.DeleteDatasetListener.handleMessage(DeleteDatasetListener.java:53)
        at org.gbif.occurrence.cli.dataset.DeleteDatasetListener.handleMessage(DeleteDatasetListener.java:26)
        at org.gbif.common.messaging.MessageConsumer.handleCallback(MessageConsumer.java:101)
        at org.gbif.common.messaging.MessageConsumer.handleDelivery(MessageConsumer.java:65)
        at com.rabbitmq.client.impl.ConsumerDispatcher$4.run(ConsumerDispatcher.java:121)
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Fri Apr 06 21:05:55 CEST 2018, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=60303: row '4fa7b334-ce0d-4e88-aaae-2e0c138d049e|URN:catalog:CLO:EBIRD:OBS99855446' on table 'prod_e_occurrence_lookup' at region=prod_e_occurrence_lookup,4fa7b334-ce0d-4e88-aaae-2e0c138d049e|URN:catalog:CLO:EBIRD:OBS99855446,1447096271601.e68ff045ebd8d972167b9bf67efb72d0., hostname=c5n3.gbif.org,60020,1517415927036, seqNum=23123276

        at org.apache.hadoop.hbase.client.RpcRetryingCallerWithReadReplicas.throwEnrichedException(RpcRetryingCallerWithReadReplicas.java:286)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:231)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas.call(ScannerCallableWithReplicas.java:61)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:210)
        at org.apache.hadoop.hbase.client.ClientScanner.call(ClientScanner.java:327)
        at org.apache.hadoop.hbase.client.ClientScanner.loadCache(ClientScanner.java:410)
        at org.apache.hadoop.hbase.client.ClientScanner.next(ClientScanner.java:371)
        at org.apache.hadoop.hbase.client.AbstractClientScanner$1.hasNext(AbstractClientScanner.java:94)
        ... 11 common frames omitted
Caused by: java.net.SocketTimeoutException: callTimeout=60000, callDuration=60303: row '4fa7b334-ce0d-4e88-aaae-2e0c138d049e|URN:catalog:CLO:EBIRD:OBS99855446' on table 'prod_e_occurrence_lookup' at region=prod_e_occurrence_lookup,4fa7b334-ce0d-4e88-aaae-2e0c138d049e|URN:catalog:CLO:EBIRD:OBS99855446,1447096271601.e68ff045ebd8d972167b9bf67efb72d0., hostname=c5n3.gbif.org,60020,1517415927036, seqNum=23123276
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:169)
        at org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture.run(ResultBoundedCompletionService.java:80)
        ... 3 common frames omitted
Caused by: java.io.IOException: Call to c5n3.gbif.org/130.225.43.93:60020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call id=13589, waitTime=60001, operationTimeout=60000 expired.
        at org.apache.hadoop.hbase.ipc.AbstractRpcClient.wrapException(AbstractRpcClient.java:292)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1273)
        at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:227)
        at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:336)
        at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.scan(ClientProtos.java:34094)
        at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:220)
        at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:65)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:210)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:381)
        at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:355)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:136)
        ... 4 common frames omitted
Caused by: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call id=13589, waitTime=60001, operationTimeout=60000 expired.
        at org.apache.hadoop.hbase.ipc.Call.checkAndSetTimeout(Call.java:73)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1247)
        ... 13 common frames omitted
```

**Comment by MattBlissett** [comment]
No longer part of occurrence project.
