### ISSUE TITLE
Occurrences not persisting to HBase

### ISSUE THREAD

**Issue by MattBlissett** [gbif/occurrence#51]
Occurrences from https://www.gbif.org/dataset/713088d4-f762-11e1-a439-00145eb45e9a are mostly absent from SOLR, and are not persisting properly to HBase.

Errors from CLI logs:

```
INFO  [06-20 15:35:18,998+0200] [occurrence_interp-8] org.apache.hadoop.hbase.client.RpcRetryingCaller: 713088d4-f762-11e1-a439-00145eb45e9a Call exception, tries=25, retries=35, started=370301 ms ago, cancelled=false, msg=row '�w�' on table 'prod_e_occurrence' at region=prod_e_occurrence,\x0Cj]\xF1,1525858177982.e7bac5fee3ef15baf15d904b633cc4a3., hostname=c5n5.gbif.org,60020,1525805626778, seqNum=5727391381
```

```
WARN  [06-20 15:40:11,102+0200] [occurrence_interp-4] org.gbif.common.messaging.MessageConsumer: 713088d4-f762-11e1-a439-00145eb45e9a Error handling message [2055566] of type [VerbatimPersistedMessage]. Reject and send a nack
org.gbif.api.exception.ServiceUnavailableException: Could not access HBase
        at org.gbif.occurrence.persistence.OccurrencePersistenceServiceImpl.updateOcc(OccurrencePersistenceServiceImpl.java:211)
        at org.gbif.occurrence.persistence.OccurrencePersistenceServiceImpl.update(OccurrencePersistenceServiceImpl.java:149)
        at org.gbif.occurrence.processor.InterpretedProcessor.buildInterpreted(InterpretedProcessor.java:124)
        at org.gbif.occurrence.processor.messaging.VerbatimPersistedListener.handleMessage(VerbatimPersistedListener.java:43)
        at org.gbif.occurrence.processor.messaging.VerbatimPersistedListener.handleMessage(VerbatimPersistedListener.java:23)
        at org.gbif.common.messaging.MessageConsumer.handleCallback(MessageConsumer.java:101)
        at org.gbif.common.messaging.MessageConsumer.handleDelivery(MessageConsumer.java:65)
        at com.rabbitmq.client.impl.ConsumerDispatcher$4.run(ConsumerDispatcher.java:121)
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=35, exceptions:
Wed Jun 20 15:30:59 CEST 2018, RpcRetryingCaller{globalStartTime=1529501459637, pause=100, retries=35}, java.io.IOException: java.io.IOException
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2228)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:112)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:183)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:163)
Caused by: java.lang.NullPointerException
```

I orphan-rescued it to make it easier to try and recover it.

**Comment by timrobertson100** [comment]
The line throwing the NPE:
https://github.com/gbif/occurrence/blob/33ec2aa490251535e5a446924b759ad384efd57b/occurrence-persistence/src/main/java/org/gbif/occurrence/persistence/OccurrencePersistenceServiceImpl.java#L211

This has to be `buildRowUpdate(occ);` returning a null object

**Comment by MattBlissett** [comment]
Duplicate of https://github.com/gbif/portal-feedback/issues/1441
